backend/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("games.urls")),
    path("data-import/", include("dataimport.urls")),
    path('users/', include('django.contrib.auth.urls')),
]

backend/dataimport/urls.py
from django.urls import path
from .views import import_data, import_players, data_imported

urlpatterns = [
    path('', import_data, name='import_game_data'),
    path('import-players', import_players, name='import_players'),
    path('data-imported', data_imported, name='data_imported')
]

backend/games/urls.py
from django.urls import path
from .views import (
    ListGame,
    DetailGame,
    ListTeam,
    DetailTeam,
    ListTeamStat,
    DetailTeamStat,
    ListPlayer,
    DetailPlayer,
    ListPlayerStat,
    DetailPlayerStat,
    ListStat,
    DetailStat,
    ListPlayerStatSum,
    DetailPlayerStatSum,
    GameStatView,
    PlayerStatSumView,
)

urlpatterns = [
    path("games/", ListGame.as_view()),
    path("games/<int:pk>/", DetailGame.as_view()),
    path("teams/", ListTeam.as_view()),
    path("teams/<int:pk>/", DetailTeam.as_view()),
    path("team-stats/", ListTeamStat.as_view()),
    path("team-stats/<int:pk>/", DetailTeamStat.as_view()),
    path("players/", ListPlayer.as_view()),
    path("players/<int:pk>/", DetailPlayer.as_view()),
    path("players-stat/", ListPlayerStat.as_view()),
    path("players-stat/<int:pk>/", DetailPlayerStat.as_view()),
    path("stats/", ListStat.as_view()),
    path("stats/<int:pk>/", DetailStat.as_view()),
    path("player-stat-sum/", ListPlayerStatSum.as_view()),
    path("player-stat-sum/<int:pk>/", DetailPlayerStatSum.as_view()),
    path('game-stats/game_id=<int:game_id>/', GameStatView.as_view(), name='game-stats'),
    path('player-stats-sum/game_id=<int:game_id>/', PlayerStatSumView.as_view(), name='player-stats-sum'),
]

backend/dataimport/forms.py
from django import forms
from django.urls import reverse_lazy
from games.models import Team

class DataImportForm(forms.Form):
    game_date = forms.DateField()
    home_team_name = forms.ChoiceField(choices=[])
    away_team_name = forms.ChoiceField(choices=[])
    home_team_csv = forms.FileField()
    away_team_csv = forms.FileField()

    def __init__(self, *args, **kwargs):
        super(DataImportForm, self).__init__(*args, **kwargs)
        self.fields['home_team_name'].choices = self.get_team_choices()
        self.fields['away_team_name'].choices = self.get_team_choices()

    def get_team_choices(self):
        teams = Team.objects.all()
        choices = [('', 'Select a team')]
        choices += [(team.name, team.name) for team in teams]
        return choices

    def get_add_team_url(self):
        return reverse_lazy('import_players')


class PlayerImportForm(forms.Form):
    team = forms.CharField(label='Team Name', max_length=100)
    player_csv = forms.FileField(label='Player CSV')

backend/dataimport/views.py
from pyexpat.errors import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
import csv
import io
from games.models import Game, Team, Player, PlayerStat, PlayerStatSum, TeamStat
from .forms import DataImportForm, PlayerImportForm


@login_required
def import_data(request):
    if request.method == "POST":
        form = DataImportForm(request.POST, request.FILES)
        if form.is_valid():
            # save game date game_date
            game_date = form.cleaned_data["game_date"]

            # save home team
            home_team_name = form.cleaned_data["home_team_name"]
            home_team, created = Team.objects.get_or_create(name=home_team_name)

            away_team_name = form.cleaned_data["away_team_name"]
            away_team, created = Team.objects.get_or_create(name=away_team_name)

            # create game
            game, created = Game.objects.get_or_create(
                date=game_date, home_team=home_team, away_team=away_team
            )

            # process the uploaded file
            home_team_csv = request.FILES["home_team_csv"]
            home_decoded_file = home_team_csv.read().decode("utf-8").splitlines()

            home_reader = csv.DictReader(home_decoded_file)
            for row in home_reader:
                # create player performance
                home_data = {
                    "shots": row["Shots"],
                    "sca": row["SCA"],
                    "touches": row["Touches"],
                    "passes": row["Passes"],
                    "carries": row["Carries"],
                    "tackled": row["Tackled"],
                    "interceptions": row["Interceptions"],
                    "blocks": row["Blocks"],
                }
                home_data_sum = {"attack": row["Attack"], "defense": row["Defense"]}
                home_player, created = Player.objects.get_or_create(name=row[""], team=home_team)
                home_performance, created = PlayerStat.objects.get_or_create(
                    game=game, player=home_player, defaults=home_data
                )
                home_performance_sum, created = PlayerStatSum.objects.get_or_create(
                    game=game, player=home_player, defaults=home_data_sum)

            away_team_csv = request.FILES["away_team_csv"]
            away_decoded_file = away_team_csv.read().decode("utf-8").splitlines()

            away_reader = csv.DictReader(away_decoded_file)
            for row in away_reader:
                # create player performance
                away_data = {
                    "shots": row["Shots"],
                    "sca": row["SCA"],
                    "touches": row["Touches"],
                    "passes": row["Passes"],
                    "carries": row["Carries"],
                    "tackled": row["Tackled"],
                    "interceptions": row["Interceptions"],
                    "blocks": row["Blocks"],
                }
                away_data_sum = {"attack": row["Attack"], "defense": row["Defense"]}

                away_player, created = Player.objects.get_or_create(name=row[""], team=away_team)
                away_performance, created = PlayerStat.objects.get_or_create(
                    game=game, player=away_player, defaults=away_data)
                away_performance_sum, created = PlayerStatSum.objects.get_or_create(
                    game=game, player=away_player, defaults=away_data_sum)
            # messages.success(request, 'Data imported successfully')
            return redirect("data_imported")
    else:
        form = DataImportForm()

    context = {"form": form}
    return render(request, "import-game.html", context)

@login_required
def import_players(request):
    if request.method == "POST":
        form = PlayerImportForm(request.POST, request.FILES)
        if form.is_valid():
            team = form.cleaned_data["team"]
            team, created = Team.objects.get_or_create(name=team)
            # process the uploaded file
            player_csv= request.FILES["player_csv"]
            player_decoded_file = player_csv.read().decode("utf-8").splitlines()

            player_reader = csv.DictReader(player_decoded_file)
            for row in player_reader:
                player = Player.objects.create(name=row["Player"], team=team)
            return redirect("import_game_data")
    else:
        form = PlayerImportForm()

    context = {"form": form}
    return render(request, "import-players.html", context)


def data_imported(request):
    return render(request, "data_imported.html")

backend/dataimport/templates/data_imported.html
{% extends 'base.html' %}

{% block content %}
  <h1>Data Imported</h1>
  {# button add another game data #}
  <a href="{% url 'import_game_data' %}">Add another game data</a>
{% endblock %}

backend/dataimport/templates/import-game.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<title>Add Game Statistics Data</title>
<div class="container mt-5">
	<div class="row justify-content-center">
		<div class="col-12 text-center">
			<h1>Add Game Statisitcs Data</h1>
			{% if messages %}
				<ul class="messages">
					{% for message in messages %}
						<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
					{% endfor %}
				</ul>
			{% endif %}
		</div>
	</div>

	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="row justify-content-center mb-4">
			<div class="col-12 col-md-6">
				<div class="card">
					<div class="card-body">
						<div class="form-group">
							<label for="id_game_date">Game Date</label>
							{{ form.game_date }}
						</div>
						<div class="form-group">
							<label for="id_home_team_name">Home Team Name</label>
							{{ form.home_team_name }}
						</div>
						<div class="form-group">
							<label for="id_away_team_name">Away Team Name</label>
							{{ form.away_team_name }}
						</div>
						<a href="{{ form.get_add_team_url }}">Team not in the list? Add new one</a>
					</div>
				</div>
			</div>
		</div>
		<div class="row justify-content-center mb-4">
			<div class="col-12 col-md-6">
				<div class="card">
					<div class="card-body">
						<div class="form-group">
							<label for="id_home_team_csv">Home Team CSV</label>
							{{ form.home_team_csv }}
						</div>
						<div class="form-group">
							<label for="id_away_team_csv">Away Team CSV</label>
							{{ form.away_team_csv }}
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row justify-content-center">
			<div class="col-12 col-md-6 text-right">
				<button class="btn btn-primary" type="submit">Import Data</button>
			</div>
		</div>
	</form>
</div>

{% endblock %}

{% block script %}
<script>
	// Add the following script after the form rendering
	document.getElementById("id_game_date").type = "date";
</script>
{% endblock script %}

backend/dataimport/templates/import-players.html
{% extends "base.html" %}

{% block content %}
<title>Add Team and Players List</title>
<div class="container mt-5">
	<div class="row justify-content-center mb-4">
		<div class="col-md-12 text-center">
			<h1>Add Team and Players List</h1>
			{% if messages %}
			<ul class="messages">
				{% for message in messages %}
				<li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
					{% endfor %}
			</ul>
			{% endif %}
		</div>
	</div>
	<form method="post" enctype="multipart/form-data">
		<div class="row justify-content-center mb-4">
			<div class="col-12 col-md-6">
				<div class="card">
					<div class="card-body">
						{% csrf_token %}
						{{ form.as_p }}
					</div>
				</div>
			</div>
		</div>
		<div class="row justify-content-center mb-4">
			<div class="col-12 col-md-6 text-right">
				<button class="btn btn-primary" type="submit">Save Team</button>
			</div>
	</form>
</div>

{% endblock %}